<?
	include("../../../database.php");

	$wonum = $_POST['wonum'];

	$sql = "SELECT
		        DISTINCT CHILD.WONUM,
		        CHILD.WORKORDERID,
		        CHILD.STATUS,
		        CHILD.DTE_SUBTYPE,
		        CHILD.DTE_BUCKET,
		        CHILD.WORKTYPE,
		        CHILD.WORKLOCATION,
		        CHILD.DESCRIPTION,
		        CHILD.PARENT,
		        EST.TOTALCOST,
		        EST.LBR_HR,
		        EST.MATLCOSTIN,
		        EST.LBRCOSTIN,
		        EST.TOOLCOSTIN,
		        EST.LDGCOST,
		        EST.TOTALDEFERREDCOST,
		        EST.REQUESTNUM,
		        EST.ESTVERSION
		    FROM(
		        SELECT * FROM WORKORDER@MAXIMO
		        WHERE WONUM = '{$wonum}'
		        AND ISTASK = 1
		    )TASK
		    LEFT JOIN(
		        SELECT * FROM WORKORDER@MAXIMO
		    )CHILD ON CHILD.WONUM = TASK.PARENT
		    LEFT JOIN(
		        SELECT * FROM PLUSDESTCONTROL@MAXIMO 
		    )CU ON CU.MASTERWONUM = CHILD.WONUM
		    LEFT JOIN(
		     SELECT
		         ESTIMATETYPE,
		         STATUS,
		         REQUESTNUM,
		         MAX(ESTVERSION) AS ESTVERSION
		     FROM PLUSDESTVERSION@MAXIMO
		     WHERE ESTIMATETYPE = 'DESIGN'
		     AND STATUS = 'ACCEPTED'
		     GROUP BY ESTIMATETYPE, STATUS, MATLCOSTIN, LBRCOSTIN, TOOLCOSTIN, LDGCOST, TOTALDEFERREDCOST, REQUESTNUM
		    )VERSION ON VERSION.REQUESTNUM = CU.REQUESTNUM
		    LEFT JOIN(
		        SELECT (MATLCOSTIN+LBRCOSTIN+TOOLCOSTIN+LDGCOST+TOTALDEFERREDCOST) AS TOTALCOST, (LBRHRSITEIN+LBRHRSITEOUT+LBRHRSOFFSITEIN) AS LBR_HR, MATLCOSTIN, LBRCOSTIN, TOOLCOSTIN, LDGCOST, TOTALDEFERREDCOST, REQUESTNUM, ESTVERSION
		        FROM PLUSDESTVERSION@MAXIMO
		    )EST ON (EST.ESTVERSION = VERSION.ESTVERSION AND EST.REQUESTNUM = CU.REQUESTNUM)";
	$vars = $prod->fetch($sql);

	echo $vars['TOTALCOST'];
?>